### ISSUE TITLE
2021-01-19 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1934]
- [x] set THC/NJR essay time
- [x] find times for next meeting with Nick
- [x] review AWS public s3 buckets --> #1936 created
- [x] Nick's email about new deployment suggestion #1935
- [x] sandbox update - issue tracker deployment? https://github.com/cu-mkp/issue-tracker-archive/issues/7
- [x] issue tracker archive - review open issues https://github.com/cu-mkp/issue-tracker-archive/issues
- [x] build issue tracker on THC machine https://github.com/cu-mkp/issue-tracker-archive/issues/9
- [ ] automated checks of metadata
- [x] lxml dependabot update https://github.com/cu-mkp/manuscript-object/pull/66
- [x] #1932 DigitalOcean droplet check
- [x] review updates to edition640 since June 2020 for M&K update in Feb

**Comment by njr2128** [comment]
last remaining item (automated checks) moved to #1937 tasks
