### ISSUE TITLE
2021-02-01 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1939]
- [x] run update.py to check for derivative file fix (https://github.com/cu-mkp/manuscript-object/issues/70) 
- [x] create set of instructions for changing any derivative files (see comment below)
- [x] unit testing --> is https://github.com/cu-mkp/manuscript-object/issues/51 (code checks as developing manuscript-object)
- [x] regression testing by updating travis --> #1941 (checks AFTER update.py is run)
- [x] automated checks of metadata (from last time) --> https://github.com/cu-mkp/manuscript-object/issues/48 (entry-metadata has complete and accurate values, which can be dealt with at either stage, either at level of https://github.com/cu-mkp/manuscript-object/issues/51 and #1941)
- [x] review DCE redesign
- [x] https://github.com/cu-mkp/manuscript-object/issues/68 (release of manuscript-object) --> later
- [x] open issues? set priorities
- [x] travis CI shenanigans - #1942 and #1947
- [x] add to READ.me files how to properly run update.py using a branch

**Comment by njr2128** [comment]
@gschare will create place to put this:
making changes to derivative files in m-k-manuscript-data:
```
cd [m-k-manuscript-data]
git fetch
git pull
git checkout -b [name of branch] {checkout a branch}
cd [manuscript-object]
git fetch
git pull
python(+version) update.py
cd [m-k-manuscript-data]
git add . 
git commit -m ‘#[issue##]: [commit message]’
git push -u origin [branchname]
```

**Comment by gschare** [comment]
Maybe put this in a README.md in the root of the repo?

Making changes to derivative files in `m-k-manuscript-data`:

1. `cd` to `m-k-manuscript-data` directory
2. `git fetch`
3. `git pull`
4. Checkout a branch: `git checkout -b [name of branch]`
5. `cd` to `manuscript-object` directory
6. `git fetch`
7. `git pull`
8. Run update.py: `python3 update.py` (might need to use `python3.8`, e.g., if you have more than one version installed)
9. `cd` back to `m-k-manuscript-data` directory
10. `git add .`
11. `git commit -m '#[issue##]: [commit message]'`
12. `git push -u origin [name of branch]`

**Comment by njr2128** [comment]
@gschare - yes. Let's put in both manuscript-object and m-k-manuscript-data

**Comment by njr2128** [comment]
All items have been documented as shown in the edited list above
