### ISSUE TITLE
2021-02-16 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1949]
- [x] https://github.com/cu-mkp/manuscript-object/issues/68 (draft release of object)
- [x] https://github.com/cu-mkp/manuscript-object/issues/76 (set goals/design for object code) --> moved to #1959 
- [x] billing alert for digitalOcean - confirm active buckets are necessary
- [x] makingandknowing.org site down on Thu, Feb 11, 12:01 AM (reported by M&K collaborator). Check downages?
     - THC (through auto bot) got downage report at this time. Nothing major. Not much we can do (various other outages too)
- [ ] #1952 (github and oxygen protocol)
- [x]  #1953 (schema "full" attribute)
- [x] manuscript-object pull requests
- [x] travis removal #1947 and check the efficacy/completeness of Github Actions replacement
     - tested by NJR pull requests #1957, #1955, and #1954 which all passed
     - this, however, raised the issue of #1787 because no error was thrown for the schema missing attribute value of full (as in #1953 issue above)
- [x] review replacing xmllint with jing (#1787)
