### ISSUE TITLE
2021-02-22 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1959]
- [x] update from Greg
- [x] github coupon email
- [ ] cu-mkp/manuscript-object#76 (set goals/design for object code)
- [x] review jing check (#1787)
- [x] issue tracker archive work by greg (esp. https://github.com/cu-mkp/issue-tracker-archive/issues/13) - pull requests seen the same as issues
- [x] update from Libraries meeting earlier today -- for Terry - Crossref dois (may affect #1912) and update for Pamela - domain name

**Comment by gschare** [comment]
[ ] Merge PR #1960

**Comment by njr2128** [comment]
for next time: change meeting time going forward

**Comment by njr2128** [comment]
all moved to #1965
