### ISSUE TITLE
areas of work (spring 2021 onward)

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1964]
**Bolded items are ones in active development as of this posting**

- **sandbox materials** (jupyter notebooks, EP intern work, Clement?, voyant --https://github.com/cu-mkp/sandbox/issues)
- sandbox website (interface, infrastructure, deployment, maintenance, etc)
- **manuscript-object maintenance and development**
- Project archives
     - field notes
     - **issue tracker**
     - github repository for manuscript-data, workshop edition, and GR8975 edition (Terry has done this but we should review - https://zenodo.org/record/1197521#.YDfP4JNKjeQ; guide for working with zenodo+github:https://guides.github.com/activities/citable-code/ and https://guides.lib.berkeley.edu/citeyourcode
; also consider AC as per conversation with Libraries)
     - manuscript-object and making-and-knowing-edition
     - backups in AWS (flickr, GD, wiki site)
     - Flickr elsewhere? E.g., zenodo - see Plazi's image archives: https://zenodo.org/communities/biosyslit/search?page=1&size=20&q=&type=image (274,197 images)

**Comment by njr2128** [comment]
Update as of this posting

- [ ] issue tracker archive
     - [ ] Greg is building a static site generator for it
     - [ ] to do: add github events to json; and downloading some github user content? https://github.com/cu-mkp/issue-tracker-archive/issues/10
     - [ ] THC+NJR to do: https://github.com/cu-mkp/issue-tracker-archive/issues/8
     - [ ] decision: deploy as part of sandbox (for hosting considerations at least for now)
- [ ] field notes
    - [ ] https://github.com/cu-mkp/fieldnotes/issues/6 (fixing where we left off in Aug 2020)
- [ ] sandbox content
    - [ ] EP interns, Greg, Clement, and some NJR work are up and running: https://cu-mkp.github.io/sandbox/ 
- [ ] sandbox interface and design
    - [ ] need to spec and make decisions
