### ISSUE TITLE
2021-03-11 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1967]
- [x] update from Greg
- [ ]  cu-mkp/manuscript-object#76 (set goals, etc)
- [x]  change meeting time (need to wait for PHS)
- [x]  #1964: areas of work (spring 2021 onward)
- [x] review AWS Columbia email (sent to NJR) about mandatory enabling of new features for CUIT-paid accounts
     - survey completed. Just need to wait for CUIT/AWS invitation to accept 
- [x] For review together (on print version of the DCE): https://solar.lowtechmagazine.com/2019/03/printed-website.html
     - moved to #1968 
- [x] Ask Terry about Kermit video copyright issue

**Comment by njr2128** [comment]
Another minimal computing project: mini comp (eg raspberry pi) with solar power to power DCE site?

**Comment by njr2128** [comment]
Book of interest: https://press.uchicago.edu/ucp/books/book/chicago/T/bo35612006.html
Thrifty Science: MAKING THE MOST OF MATERIALS IN THE HISTORY OF EXPERIMENT by SIMON WERRETT

**Comment by njr2128** [comment]
For next time:
- [ ]  cu-mkp/manuscript-object#76 (set goals, etc)
- [ ]  #1964: areas of work (spring 2021 onward)
- [ ] prioritize putting up Dana+Roni's stuff to sandbox
- [ ] brainstorm about sandbox things (https://github.com/cu-mkp/manuscript-object/issues/1) and https://github.com/cu-mkp/sandbox/issues

**Comment by njr2128** [comment]
moved to #1971
