### ISSUE TITLE
2021-03-16 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1971]
- [ ]  cu-mkp/manuscript-object#76 (set goals, etc)
- [ ]  #1964: areas of work (spring 2021 onward)
- [ ] prioritize putting up Dana+Roni's stuff to sandbox
- [ ] brainstorm about sandbox things (https://github.com/cu-mkp/manuscript-object/issues/1) and https://github.com/cu-mkp/sandbox/issues

**Comment by njr2128** [comment]
for next time, figure out if this was ever resolved:
"I can't remember if this is already an issue, but in List of Entries, the titles that have author deletions are not correctly rendered (no deletions), see for example fol. 6v."

**Comment by njr2128** [comment]
moved to #1976
