### ISSUE TITLE
2021-03-30 + 2021-04-06 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1976]
carrying over from #1971:
- [x] review Performant re-redesign (with Caroline)
- [x] update from Greg?
- [x] Follow-up  to EP sandbox additions
- [ ]  cu-mkp/manuscript-object#76 (set goals, etc)
- [x]  #1964: areas of work (spring 2021 onward)
     - [x] see updates commented to issue 
- [x] brainstorm about sandbox things (https://github.com/cu-mkp/manuscript-object/issues/1) and https://github.com/cu-mkp/sandbox/issues

**Comment by njr2128** [comment]
For next time -- i think return to Field Notes?

**Comment by njr2128** [comment]
2021-04-06:
- [ ] review field notes status and set goals
     - [ ] see https://github.com/cu-mkp/fieldnotes/issues/6
- [ ] update from greg
- [ ] review sandbox

**Comment by njr2128** [comment]
For next check in:
- review deployment overview process, summarized by THC+NJR in the GD doc named "edition640+fieldnotes_DNS+deployments", and identify questions for Nick

**Comment by njr2128** [comment]
done here
