### ISSUE TITLE
2021-04-20 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1984]
- [x] sandbox: identify SP19 student final project files https://github.com/cu-mkp/sandbox/issues/18
- [x] sandbox: add SP19 final projects to sandbox (figure out what format, conversions, etc) https://github.com/cu-mkp/sandbox/issues/18
       - [ ] ---> pdf to be mounted as is. Word docs to be converted to pdfs and dealt with in the same way. For content that is not in the pdfs, figure out what is missing (if needed) and treat on case by case basis
- [x] fieldnotes: get Greg back into AWS (need to find ARN name or something)
- [x] fieldnotes: update from Greg
- [x] delete unused S3 bucket #1978 
- [x] create subdomain #1980
