### ISSUE TITLE
2021-05-06 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1987]
- [x] staging redesign review?
- [x] AWS email --> waiting to enable "all features"/ accept the invitation in S3 until we hear back from faculty contact Michael (Pamela is emailing him now)
- [x] broken images in sandbox? (https://github.com/cu-mkp/sandbox/issues/25)
- [x] sandbox - add SP19 DH projects (https://github.com/cu-mkp/sandbox/issues/18)
- [x] sandbox - add AR/VR stuff (https://github.com/cu-mkp/sandbox/issues/20)
- [x] fieldnotes check-in
- [x] Greg timesheet check - account for April
