### ISSUE TITLE
2021-05-18 tasks thru 2021-07-20

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1988]
- [x] Review M&K redesign on staging (see notes in most recent Performant Meeting Notes
- [x] Ready for meeting with Nick + Chris tomorrow (May 19)
- [x] Sandbox --> start to think about interface, design (https://github.com/cu-mkp/sandbox/issues/16)
- [x] fieldnotes --> finished and closed https://github.com/cu-mkp/fieldnotes/issues/6 [2021-05-25], and next to do:
      - https://github.com/cu-mkp/fieldnotes/issues/12
      - https://github.com/cu-mkp/fieldnotes/issues/13

**Comment by njr2128** [comment]
from annotation-meatadata folder URLs, list contents of the folder directory. If possible, also include contents of any folders within the original folder (these would be the illustrations)

**Comment by njr2128** [comment]
these have been moved to:
https://github.com/cu-mkp/GD_comment/issues/7 (remove access)
https://github.com/cu-mkp/GD_comment/issues/8 (file tree of annotation folder)

**Comment by njr2128** [comment]
Next week:
- Terry run google drive permission deletion code (make sure we have all documentation or knowledge set up)

**Comment by njr2128** [comment]
Next time:
- BnF permissions; ability to transfer ownership to GE?

**Comment by njr2128** [comment]
STATUS (2021-06-22)
- fieldnotes (https://github.com/cu-mkp/fieldnotes-content) 
     - CloudFront has been updated accordingly
     - NJR to find the few missing files from FA17 (https://github.com/cu-mkp/fieldnotes-restructuring/blob/main/missing.csv)
     - mainspace has been restructured in github, but now need to deploy S3 bucket -- this will update the fieldnotes.makingandknowing.org site with the newly indexed files from the restructuring of mainspace
     - NEXT: add Fall 2018 and pre-Fall 2018 to the site
- DCE essays as html work (TBD from Nick's timeline)
- Work with Rowan
- Sandbox
     - design (https://github.com/cu-mkp/sandbox/issues/16)
     - SU21 student final projects
- issue tracker archive - come up with MVP and release it 
- Greg ongoing work (refactoring etc)
- GD: Terry to run code (https://github.com/cu-mkp/GD-code)

**Comment by njr2128** [comment]
From Libraries:
- second level domain vs. first level domain 
- want to ensure that configuring domain assignment and masking for the full edition640.makingandknowing.org domain will work on the libraries servers, and with their security certificates
- - basically, can we get our site on their servers with our domain - make sure there aren't any rerouting issues (so that they don't get rerouted to makingandknowing.org itself since edition640 is a second level domain)
- concern is that CU's unix system and security certificates may reroute any subdomains back to main domain (makingandknowing.org
- will likely need to get sysadmin group involved soon to test  in a dev environment
- - if we want Libraries to manage our domain name, Michelle is the mediator. We give her access to Bluehost and she grabs all CNAME records, and will add to CU's holdings. This is usually done with some masking due to how the servers, security certificates, but this may not need to

**Comment by njr2128** [comment]
To do:
- July newsletter update - NJR & THC, sandbox info, info about additions to DCE since Feb, personal updates

**Comment by njr2128** [comment]
Fieldnotes STATUS:

- [ ] https://github.com/cu-mkp/fieldnotes-content/issues/6 create landing page for the entire fieldnotes site
- [ ] https://github.com/cu-mkp/fieldnotes-restructuring/issues/13 fix links in index pages within each semester ("semester index pages")
- [ ] https://github.com/cu-mkp/fieldnotes-content/issues/7 landing pages for intermediate index pages

**Comment by njr2128** [comment]
To do 2021-07-20:

- [ ] compose email to Ben (NJR+THC)
- [ ] update from Rowan
- [ ] update from Greg
- [ ] fieldnotes update (https://github.com/cu-mkp/fieldnotes-restructuring/issues/17) and #1992 (add SU21 field notes)

**Comment by ps2270** [comment]
Please also review redesign in Staging

**Comment by njr2128** [comment]
all items here have been resolved or moved to other issues
