### ISSUE TITLE
2021-07-27 tasks

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1994]
Follow-up to #1988
- [x] compose email to Ben (NJR+THC) https://github.com/cu-mkp/m-k-manuscript-data/issues/1991, see also GD doc name "edition640+fieldnotes_DNS+deployments"
- [x] update from Rowan
- [x] update from Greg
- [x] fieldnotes update - review #1995, and (https://github.com/cu-mkp/fieldnotes-restructuring/issues/17) and #1992 (add SU21 field notes)
- [x] prepare fieldnotes MVP - held back by https://github.com/cu-mkp/fieldnotes-content/issues/7 landing pages for intermediate index pages, which must be completed first
- [ ] RTC subdomain -- linked up eventually to https://github.com/cu-mkp/research-teaching-companion
- [x] GD file generation https://github.com/cu-mkp/GD-code/issues/11
- [x] #1996
     - https://support.google.com/drive/answer/10729743?p=update_drives_user&visit_id=637629355053215561-1811253122&rd=1
     - Backup and Sync: https://www.reviewgeek.com/91808/google-drive-for-desktop-now-syncs-to-multiple-accounts-after-major-overhaul/ and https://arstechnica.com/gadgets/2021/07/new-google-drive-app-unifies-business-and-home-use-cases/
- [ ] Sandbox
     - design (https://github.com/cu-mkp/sandbox/issues/16)
     - SU21 student final projects
- [ ] issue tracker archive - come up with MVP and release it 
- [ ] GD: Terry to run code (https://github.com/cu-mkp/GD-code) 
- [x] https://github.com/cu-mkp/edition-webpages/pull/176

**Comment by njr2128** [comment]
closing as this is moved to #2000
