### ISSUE TITLE
Fieldnotes next steps, status: prepare MVP

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1995]
Fieldnotes STATUS:

- [ ] https://github.com/cu-mkp/fieldnotes-content/issues/6 create landing page for the entire fieldnotes site
- [ ] https://github.com/cu-mkp/fieldnotes-restructuring/issues/13 fix links in index pages within each semester ("semester index pages")
- [ ] https://github.com/cu-mkp/fieldnotes-content/issues/7 landing pages for intermediate index pages

and also review together:
- [ ] https://github.com/cu-mkp/fieldnotes-restructuring/issues/17

prepare MVP
