### ISSUE TITLE
2021-08-17 agenda (without NJR)

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1998]
For review and addition:

- [x] update from Rowan
     - timing: 1) "coding" part finished ~now-ish; 2) content with PHS to be finished ~beg of Sep
     - think about documentation
     - think about how to include in Sandbox
- [ ] https://github.com/cu-mkp/m-k-manuscript-data/issues/1995 (look at issue for next steps)
- [x] https://github.com/cu-mkp/GD-code/issues/11 (need files for FA21 class)
- [x] email to Ben https://github.com/cu-mkp/m-k-manuscript-data/issues/1991
- [ ] If there is time, review open tasks in https://github.com/cu-mkp/m-k-manuscript-data/issues/1994
     - perhaps brainstorm about sandbox interface and design with Rowan

**Comment by caro27** [comment]
Greg's Code
- @njr2128/@ps2270/CMS need to organize folders. 
- Need to give Greg the field note template. 
- will code for HCR powerpoint. 
- what to do if students drop or add? drop is easy to delete folder. adding is slightly harder. running again creates a new folder. 
- wait until the week before the class starts to run the script. 
- will be its own repo (gd-generate-semester). need to clone. will need help running on my new machine. CMS will need help setting up Python from Terry and NJR.

**Comment by ps2270** [comment]
Greg's Code UPDATED MEETING NOTES:

   -  NJR/PHS/CMS need to organize folders.

 -   what to do if students drop or add? drop is easy to delete folder. we can add students at any time.
 -   wait until the week before the class starts to run the script.
-    will be its own repo (gd-generate-semester). need to clone. 
-  CMS & PHS will need help running on machineS. CMS &PHS will need help setting up Python from Terry and NJR.
Terry, Pamela, Caroline will have an install fest and go over generation instructions again

**Comment by njr2128** [comment]
New repo: https://github.com/cu-mkp/gd-generate-semester

**Comment by njr2128** [comment]
closing as this is moved to #2000
